import { useMemo, useState } from 'react'
import { NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom'
import { Activity, BarChart3, Bell, ChevronDown, CircleHelp, Command, CreditCard, FileText, LayoutDashboard, Menu, Moon, Search, Settings as SettingsIcon, Sun, Users, X } from 'lucide-react'
import { useApp } from '../../context/AppContext.jsx'
import { Toast } from '../ui/index.jsx'

const links = [
  { label: 'Overview', path: '/', icon: LayoutDashboard }, { label: 'Analytics', path: '/analytics', icon: BarChart3 },
  { label: 'Customers', path: '/customers', icon: Users }, { label: 'Transactions', path: '/transactions', icon: CreditCard },
  { label: 'Reports', path: '/reports', icon: FileText },
]
export default function AppShell() {
  const [mobileOpen, setMobileOpen] = useState(false), [notifyOpen, setNotifyOpen] = useState(false), [userOpen, setUserOpen] = useState(false), [query, setQuery] = useState('')
  const { settings, setSettings, notify } = useApp(), location = useLocation(), navigate = useNavigate()
  const title = useMemo(() => links.find(item => item.path === location.pathname)?.label ?? (location.pathname === '/settings' ? 'Settings' : location.pathname === '/profile' ? 'My profile' : 'Page not found'), [location.pathname])
  const toggleTheme = () => setSettings(current => ({ ...current, theme: current.theme === 'dark' ? 'light' : 'dark' }))
  const submitSearch = (event) => { event.preventDefault(); if (query.trim()) { navigate(`/customers?search=${encodeURIComponent(query.trim())}`); setQuery('') } }
  const Sidebar = ({ mobile = false }) => <aside className={`sidebar ${mobile ? 'sidebar-mobile' : ''}`}>
    <div className="brand"><div className="brand-mark"><Activity size={19} strokeWidth={2.5} /></div><span>northstar</span><button className="icon-button sidebar-close" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X size={18} /></button></div>
    <div className="workspace-switch"><div className="workspace-avatar">N</div><div className="workspace-copy"><b>Northstar Studio</b><span>Pro plan</span></div><ChevronDown size={15} /></div>
    <div className="nav-label">WORKSPACE</div><nav className="side-nav" aria-label="Main navigation">{links.map(({ label, path, icon: Icon }) => <NavLink key={path} to={path} end={path === '/'} onClick={() => setMobileOpen(false)} className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`}><Icon size={18} /><span>{label}</span>{label === 'Transactions' && <span className="nav-count">8</span>}</NavLink>)}</nav>
    <div className="sidebar-bottom"><div className="nav-label">PREFERENCES</div><NavLink to="/settings" onClick={() => setMobileOpen(false)} className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`}><SettingsIcon size={18} /><span>Settings</span></NavLink><button className="nav-link help-link" onClick={() => notify('Help center is ready to assist you')}><CircleHelp size={18} /><span>Help center</span><span className="external-mark">↗</span></button>
      <div className="sidebar-plan"><div className="plan-icon"><Command size={16} /></div><div><b>You're on Pro</b><span>Unlock more of Northstar</span></div><button className="text-arrow" onClick={() => notify('You are already on our Pro plan')}>Upgrade</button></div>
      <button className="sidebar-user" onClick={() => navigate('/profile')}><div className="avatar avatar-small">AM</div><span className="user-meta"><b>{settings.name || 'Alex Morgan'}</b><small>{settings.email || 'alex@northstar.app'}</small></span><ChevronDown size={16} /></button>
    </div>
  </aside>
  return <div className="app-shell"><div className={`sidebar-wrap ${mobileOpen ? 'mobile-visible' : ''}`}><Sidebar mobile /></div><div className="sidebar-desktop"><Sidebar /></div><main className="main-area"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><div className="breadcrumb"><span>Workspace</span><span className="crumb-divider">/</span><b>{title}</b></div></div><div className="topbar-actions"><form className="search-box" onSubmit={submitSearch}><Search size={16} /><input aria-label="Search customers" placeholder="Search anything..." value={query} onChange={event => setQuery(event.target.value)} /><kbd>⌘ K</kbd></form><button className="icon-button theme-button" onClick={toggleTheme} aria-label="Toggle dark mode">{settings.theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button><div className="dropdown-anchor"><button className="icon-button notification-button" onClick={() => { setNotifyOpen(!notifyOpen); setUserOpen(false) }} aria-label="Notifications"><Bell size={18} /><i /></button>{notifyOpen && <div className="floating-menu notification-menu"><div className="menu-head"><b>Notifications</b><button onClick={() => { setNotifyOpen(false); notify('You are all caught up') }}>Mark all read</button></div><div className="notification-item"><span className="notification-dot blue"/><div><b>Payment received</b><p>Olivia Rhye paid $2,400.00</p><small>12 minutes ago</small></div></div><div className="notification-item"><span className="notification-dot green"/><div><b>New customer</b><p>Phoenix Baker joined your workspace</p><small>1 hour ago</small></div></div></div>}</div><div className="dropdown-anchor profile-anchor"><button className="top-profile" onClick={() => { setUserOpen(!userOpen); setNotifyOpen(false) }}><div className="avatar">AM</div><ChevronDown size={14} /></button>{userOpen && <div className="floating-menu user-menu"><button onClick={() => { navigate('/profile'); setUserOpen(false) }}>My profile</button><button onClick={() => { navigate('/settings'); setUserOpen(false) }}>Account settings</button><button onClick={() => { toggleTheme(); setUserOpen(false) }}>Toggle appearance</button></div>}</div></div></header><div className="page-content"><Outlet /></div></main><Toast /></div>
}
