import { useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Building2, Download, Eye, Mail, MoreHorizontal, Pencil, Plus, Search, Trash2, Users } from 'lucide-react'
import { Button, CustomerAvatar, EmptyState, Field, Modal, PageHeader, Pagination, Panel, StatusBadge, usePageData, Confirm } from '../components/ui/index.jsx'
import { useApp } from '../context/AppContext.jsx'
import { downloadCsv, formatDate, money } from '../utils/helpers.js'

const blank = { name: '', email: '', company: '', plan: 'Starter', status: 'Active', spent: '0', joined: new Date().toISOString().slice(0, 10) }
export default function Customers() {
  const { customers, setCustomers, notify } = useApp(), [searchParams, setSearchParams] = useSearchParams()
  const [query, setQuery] = useState(searchParams.get('search') || ''), [status, setStatus] = useState('All statuses'), [sort, setSort] = useState('Newest first')
  const [modal, setModal] = useState(null), [form, setForm] = useState(blank), [errors, setErrors] = useState({}), [confirm, setConfirm] = useState(null), [view, setView] = useState(null)
  const filtered = useMemo(() => { let result = customers.filter(item => `${item.name} ${item.email} ${item.company}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All statuses' || item.status === status)); return result.sort((a, b) => sort === 'Name A–Z' ? a.name.localeCompare(b.name) : sort === 'Spend: high to low' ? b.spent - a.spent : b.joined.localeCompare(a.joined)) }, [customers, query, status, sort])
  const { page, setPage, pageSize, shown } = usePageData(filtered, 6)
  const openCreate = () => { setForm(blank); setErrors({}); setModal('create') }
  const openEdit = (item) => { setForm({ ...item, spent: String(item.spent) }); setErrors({}); setModal(item.id) }
  const validate = () => { const next = {}; if (!form.name.trim()) next.name = 'Name is required'; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) next.email = 'Enter a valid email'; if (!form.company.trim()) next.company = 'Company is required'; setErrors(next); return !Object.keys(next).length }
  const save = (event) => { event.preventDefault(); if (!validate()) return; if (modal === 'create') { setCustomers(items => [{ ...form, id: `CUS-${Date.now().toString().slice(-5)}`, spent: Number(form.spent) }, ...items]); notify('Customer added successfully') } else { setCustomers(items => items.map(item => item.id === modal ? { ...form, spent: Number(form.spent), id: item.id } : item)); notify('Customer details updated') } setModal(null) }
  const remove = () => { setCustomers(items => items.filter(item => item.id !== confirm.id)); setConfirm(null); notify('Customer deleted') }
  const download = () => { downloadCsv('northstar-customers.csv', filtered.map(({ id, name, email, company, plan, status, spent, joined }) => ({ id, name, email, company, plan, status, spent, joined }))); notify('Customer list exported') }
  const onSearch = value => { setQuery(value); setSearchParams(value ? { search: value } : {}) }
  return <><PageHeader eyebrow="RELATIONSHIPS" title="Customers" description={`${customers.length} customers in your workspace.`}><Button variant="secondary" onClick={download}><Download size={16} /> Export</Button><Button onClick={openCreate}><Plus size={17} /> Add customer</Button></PageHeader>
    <Panel title="All customers" subtitle="Manage your customer relationships"><div className="table-toolbar"><label className="table-search"><Search size={16} /><input value={query} onChange={event => onSearch(event.target.value)} placeholder="Search customers..." aria-label="Search customers" /></label><div className="toolbar-filters"><select aria-label="Filter customer status" value={status} onChange={event => setStatus(event.target.value)}><option>All statuses</option><option>Active</option><option>Pending</option><option>Churned</option></select><select aria-label="Sort customers" value={sort} onChange={event => setSort(event.target.value)}><option>Newest first</option><option>Name A–Z</option><option>Spend: high to low</option></select></div></div>
      {shown.length ? <div className="table-scroll"><table><thead><tr><th>Customer</th><th>Company</th><th>Plan</th><th>Status</th><th>Total spent</th><th>Joined</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{shown.map(item => <tr key={item.id}><td><div className="table-person"><CustomerAvatar name={item.name} /><span><b>{item.name}</b><small>{item.email}</small></span></div></td><td>{item.company}</td><td><span className="plan-tag">{item.plan}</span></td><td><StatusBadge status={item.status} /></td><td className="amount-cell">{money(item.spent)}</td><td>{formatDate(item.joined)}</td><td><div className="row-actions"><button title="View customer" aria-label={`View ${item.name}`} onClick={() => setView(item)}><Eye size={16} /></button><button title="Edit customer" aria-label={`Edit ${item.name}`} onClick={() => openEdit(item)}><Pencil size={15} /></button><button title="Delete customer" aria-label={`Delete ${item.name}`} onClick={() => setConfirm(item)}><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div> : <EmptyState title="No customers found" description="Try another search or add a customer to get started." />}
      <Pagination page={page} setPage={setPage} total={filtered.length} pageSize={pageSize} />
    </Panel>
    {modal && <Modal title={modal === 'create' ? 'Add customer' : 'Edit customer'} subtitle="Add customer details to your workspace." onClose={() => setModal(null)}><form onSubmit={save} className="form-grid"><Field label="Full name" required error={errors.name}><input id="full-name" autoFocus value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="e.g. Taylor Morgan" /></Field><Field label="Email address" required error={errors.email}><input id="email-address" type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="name@company.com" /></Field><Field label="Company" required error={errors.company}><input id="company" value={form.company} onChange={e => setForm({ ...form, company: e.target.value })} placeholder="Company name" /></Field><Field label="Plan"><select id="plan" value={form.plan} onChange={e => setForm({ ...form, plan: e.target.value })}><option>Starter</option><option>Pro</option><option>Enterprise</option></select></Field><Field label="Status"><select id="status" value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option>Active</option><option>Pending</option><option>Churned</option></select></Field><Field label="Total spent"><input id="total-spent" type="number" min="0" value={form.spent} onChange={e => setForm({ ...form, spent: e.target.value })} /></Field><div className="modal-actions form-span"><Button type="button" variant="secondary" onClick={() => setModal(null)}>Cancel</Button><Button type="submit">{modal === 'create' ? 'Add customer' : 'Save changes'}</Button></div></form></Modal>}
    {view && <Modal title="Customer details" subtitle={view.id} onClose={() => setView(null)}><div className="customer-profile"><CustomerAvatar name={view.name} className="avatar-large"/><h3>{view.name}</h3><p>{view.company} · {view.plan} plan</p><StatusBadge status={view.status} /></div><div className="detail-list"><div><Mail size={16}/><span>Email</span><b>{view.email}</b></div><div><Building2 size={16}/><span>Company</span><b>{view.company}</b></div><div><Users size={16}/><span>Total spent</span><b>{money(view.spent)}</b></div><div><span/><span>Joined</span><b>{formatDate(view.joined)}</b></div></div><div className="modal-actions"><Button variant="secondary" onClick={() => setView(null)}>Close</Button><Button onClick={() => { setView(null); openEdit(view) }}><Pencil size={15}/> Edit customer</Button></div></Modal>}
    {confirm && <Confirm title="Delete customer?" description={`This will permanently remove ${confirm.name} from your customer list.`} onCancel={() => setConfirm(null)} onConfirm={remove} confirmLabel="Delete customer" />}
  </>
}
