import { useState } from 'react'
import { Bell, Moon, RotateCcw, Sun, UserRound } from 'lucide-react'
import { Button, Confirm, Field, PageHeader, Panel } from '../components/ui/index.jsx'
import { useApp } from '../context/AppContext.jsx'

export default function Settings() {
  const { settings, setSettings, resetDemo, notify } = useApp(), [form, setForm] = useState({ name: settings.name, email: settings.email, company: settings.company }), [confirm, setConfirm] = useState(false)
  const update = (key, value) => setSettings(current => ({ ...current, [key]: value }))
  const save = event => { event.preventDefault(); setSettings(current => ({ ...current, ...form })); notify('Settings saved successfully') }
  return <><PageHeader eyebrow="WORKSPACE" title="Settings" description="Manage your profile, preferences, and workspace."/><div className="settings-layout"><div className="settings-main"><Panel title="Profile information" subtitle="Update your personal and workspace details"><form className="settings-form" onSubmit={save}><div className="settings-profile"><div className="avatar avatar-profile">{form.name.split(' ').map(part => part[0]).slice(0, 2).join('').toUpperCase() || 'AM'}</div><div><b>Profile photo</b><span>Initials are generated from your name.</span></div></div><Field label="Full name" required><input id="full-name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required/></Field><Field label="Email address" required><input id="email-address" type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required/></Field><Field label="Workspace name"><input id="workspace-name" value={form.company} onChange={e => setForm({ ...form, company: e.target.value })}/></Field><div className="settings-save"><Button type="submit">Save changes</Button></div></form></Panel>
      <Panel title="Appearance" subtitle="Personalize how Northstar looks on this device"><div className="appearance-options"><button className={`appearance-card ${settings.theme === 'light' ? 'selected' : ''}`} onClick={() => update('theme', 'light')}><div className="appearance-preview light-preview"><Sun size={18}/><span/><span/><span/></div><b>Light</b><small>Clean and bright</small></button><button className={`appearance-card ${settings.theme === 'dark' ? 'selected' : ''}`} onClick={() => update('theme', 'dark')}><div className="appearance-preview dark-preview"><Moon size={18}/><span/><span/><span/></div><b>Dark</b><small>Easy on the eyes</small></button></div></Panel>
      <Panel title="Notifications" subtitle="Choose which updates you want to receive"><div className="preference-list"><Preference icon={Bell} title="Email notifications" description="Payment receipts and account activity" checked={settings.emailAlerts} onChange={value => update('emailAlerts', value)}/><Preference icon={UserRound} title="Weekly summary" description="A weekly snapshot of your business performance" checked={settings.weeklySummary} onChange={value => update('weeklySummary', value)}/><Preference icon={Bell} title="Product updates" description="New features, tips, and product announcements" checked={settings.productUpdates} onChange={value => update('productUpdates', value)}/></div></Panel>
      <Panel title="Demo data" subtitle="Restore the original sample customers and transactions"><div className="reset-row"><div><b>Reset demo data</b><span>This replaces your current customer and transaction lists with the original sample data.</span></div><Button variant="danger-outline" onClick={() => setConfirm(true)}><RotateCcw size={15}/> Reset data</Button></div></Panel></div><aside className="settings-aside"><div className="aside-card"><div className="aside-icon"><UserRound size={19}/></div><b>Workspace profile</b><p>You're signed in to the Northstar Studio workspace on the Pro plan.</p><div><span>Workspace</span><strong>{settings.company}</strong></div><div><span>Plan</span><strong>Pro</strong></div><div><span>Theme</span><strong>{settings.theme === 'dark' ? 'Dark mode' : 'Light mode'}</strong></div></div><div className="aside-tip"><b>Need a hand?</b><p>Visit the help center for tips on getting the most out of your workspace.</p></div></aside></div>{confirm && <Confirm title="Reset demo data?" description="This will restore the original sample customers and transactions. Your profile and preferences will stay as they are." onCancel={() => setConfirm(false)} onConfirm={() => { resetDemo(); setConfirm(false) }} confirmLabel="Reset demo data"/>}</>
}
function Preference({ icon: Icon, title, description, checked, onChange }) { return <div className="preference-row"><div className="preference-icon"><Icon size={17}/></div><div className="preference-copy"><b>{title}</b><span>{description}</span></div><button className={`switch ${checked ? 'on' : ''}`} role="switch" aria-checked={checked} aria-label={title} onClick={() => onChange(!checked)}><i/></button></div> }
