import { useMemo, useState } from 'react'
import { Download, Eye, Search } from 'lucide-react'
import { Button, CustomerAvatar, EmptyState, Modal, PageHeader, Pagination, Panel, StatusBadge, usePageData } from '../components/ui/index.jsx'
import { useApp } from '../context/AppContext.jsx'
import { downloadCsv, formatDate, money } from '../utils/helpers.js'

export default function Transactions() {
  const { transactions, setTransactions, notify } = useApp(), [query, setQuery] = useState(''), [status, setStatus] = useState('All statuses'), [sort, setSort] = useState('Newest first'), [selected, setSelected] = useState(null)
  const filtered = useMemo(() => transactions.filter(item => `${item.id} ${item.customer} ${item.email}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All statuses' || item.status === status)).sort((a, b) => sort === 'Amount: high to low' ? b.amount - a.amount : b.date.localeCompare(a.date)), [transactions, query, status, sort])
  const { page, setPage, pageSize, shown } = usePageData(filtered, 6)
  const exportCsv = () => { downloadCsv('northstar-transactions.csv', filtered); notify('Transaction CSV downloaded') }
  const updateStatus = (item, next) => { setTransactions(list => list.map(row => row.id === item.id ? { ...row, status: next } : row)); setSelected({ ...item, status: next }); notify(`Transaction marked ${next.toLowerCase()}`) }
  return <><PageHeader eyebrow="BILLING" title="Transactions" description="Review and manage all customer payments."><Button variant="secondary" onClick={exportCsv}><Download size={16} /> Export CSV</Button></PageHeader><Panel title="All transactions" subtitle={`${transactions.length} transactions recorded`}><div className="table-toolbar"><label className="table-search"><Search size={16}/><input aria-label="Search transactions" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by customer or ID..." /></label><div className="toolbar-filters"><select aria-label="Filter transaction status" value={status} onChange={e => setStatus(e.target.value)}><option>All statuses</option><option>Successful</option><option>Pending</option><option>Failed</option><option>Refunded</option></select><select aria-label="Sort transactions" value={sort} onChange={e => setSort(e.target.value)}><option>Newest first</option><option>Amount: high to low</option></select></div></div>
    {shown.length ? <div className="table-scroll"><table><thead><tr><th>Transaction</th><th>Customer</th><th>Date</th><th>Payment method</th><th>Amount</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{shown.map(item => <tr key={item.id}><td><b className="transaction-id">{item.id}</b></td><td><div className="table-person"><CustomerAvatar name={item.customer}/><span><b>{item.customer}</b><small>{item.email}</small></span></div></td><td>{formatDate(item.date)}</td><td>{item.method}</td><td className="amount-cell">{money(item.amount)}</td><td><StatusBadge status={item.status}/></td><td><button className="row-icon" aria-label={`View ${item.id}`} onClick={() => setSelected(item)}><Eye size={16}/></button></td></tr>)}</tbody></table></div> : <EmptyState title="No transactions found" description="Try adjusting your search or status filter." />}<Pagination page={page} setPage={setPage} total={filtered.length} pageSize={pageSize}/></Panel>
    {selected && <Modal title="Transaction details" subtitle={selected.id} onClose={() => setSelected(null)}><div className="transaction-total"><span>Payment amount</span><strong>{money(selected.amount)}</strong><StatusBadge status={selected.status}/></div><div className="detail-list"><div><span/><span>Customer</span><b>{selected.customer}</b></div><div><span/><span>Email</span><b>{selected.email}</b></div><div><span/><span>Date</span><b>{formatDate(selected.date)}</b></div><div><span/><span>Payment method</span><b>{selected.method}</b></div></div><label className="field"><span>Update status</span><select value={selected.status} onChange={e => updateStatus(selected, e.target.value)}><option>Successful</option><option>Pending</option><option>Failed</option><option>Refunded</option></select></label><div className="modal-actions"><Button variant="secondary" onClick={() => setSelected(null)}>Close</Button></div></Modal>}
  </>
}
