import { useState } from 'react'
import { Check, ChevronLeft, ChevronRight, X } from 'lucide-react'
import { useApp } from '../../context/AppContext.jsx'
import { money } from '../../utils/helpers.js'

export function PageHeader({ eyebrow, title, description, children }) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description && <p>{description}</p>}</div><div className="header-actions">{children}</div></div> }
export function Panel({ title, subtitle, action, children, className = '' }) { return <section className={`panel ${className}`}><div className="panel-heading"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>{children}</section> }
export function Button({ children, variant = 'primary', className = '', ...props }) { return <button className={`button button-${variant} ${className}`} {...props}>{children}</button> }
export function StatCard({ label, value, change, icon: Icon, tone = 'purple', note }) { return <article className="stat-card"><div className="stat-top"><span>{label}</span><div className={`stat-icon tone-${tone}`}><Icon size={18} /></div></div><div className="stat-value">{value}</div><div className="stat-foot"><span className="growth-pill">↗ {change}</span><span>{note || 'vs. last month'}</span></div></article> }
export function StatusBadge({ status }) { const type = /active|successful|paid|completed/i.test(status) ? 'success' : /pending|processing/i.test(status) ? 'warning' : /failed|churned|canceled/i.test(status) ? 'danger' : 'neutral'; return <span className={`status-badge ${type}`}><i />{status}</span> }
export function EmptyState({ title = 'Nothing to show yet', description = 'Try adjusting your filters or add a new item.' }) { return <div className="empty-state"><div className="empty-art">⌁</div><b>{title}</b><p>{description}</p></div> }
export function Pagination({ page, setPage, total, pageSize }) { const pages = Math.max(1, Math.ceil(total / pageSize)); return <div className="pagination"><span>Showing <b>{total ? (page - 1) * pageSize + 1 : 0}-{Math.min(page * pageSize, total)}</b> of <b>{total}</b></span><div><button aria-label="Previous page" disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><span>Page {page} of {pages}</span><button aria-label="Next page" disabled={page >= pages} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div></div> }
export function Modal({ title, subtitle, onClose, children, wide = false }) { return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className={`modal ${wide ? 'modal-wide' : ''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-heading"><div><h2 id="modal-title">{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={18} /></button></div>{children}</section></div> }
export function Toast() { const { toast } = useApp(); if (!toast) return null; return <div className={`toast toast-${toast.type}`} role="status"><span className="toast-check"><Check size={16} /></span>{toast.message}</div> }
export function Confirm({ title, description, onCancel, onConfirm, confirmLabel = 'Confirm' }) { return <Modal title={title} subtitle={description} onClose={onCancel}><div className="modal-actions"><Button variant="secondary" onClick={onCancel}>Cancel</Button><Button variant="danger" onClick={onConfirm}>{confirmLabel}</Button></div></Modal> }
export function CustomerAvatar({ name, className = '' }) { const initials = String(name || 'N').split(' ').map(part => part[0]).slice(0, 2).join('').toUpperCase(); const colors = ['#e5e3ff', '#dcfce7', '#ffead5', '#ffe1e8', '#d8f3ff']; const index = name ? name.charCodeAt(0) % colors.length : 0; return <span className={`customer-avatar ${className}`} style={{ backgroundColor: colors[index], color: '#4338ca' }}>{initials}</span> }
export function TableEmpty({ colspan, text = 'No results found' }) { return <tr><td colSpan={colspan}><EmptyState title={text} /></td></tr> }
export function Field({ label, error, required, children }) { const id = label.toLowerCase().replace(/\s+/g, '-'); return <label className="field" htmlFor={id}><span>{label}{required && <em> *</em>}</span>{children}{error && <small className="field-error">{error}</small>}</label> }
export function Amount({ value }) { return <span className="amount-cell">{money(value)}</span> }
export function usePageData(items, pageSize = 6) { const [page, setPage] = useState(1); const pages = Math.max(1, Math.ceil(items.length / pageSize)); const current = Math.min(page, pages); return { page: current, setPage, pageSize, shown: items.slice((current - 1) * pageSize, current * pageSize) } }
